# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.TimeField(default=datetime.datetime(2017, 3, 3, 5, 47, 24, 309648, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
